language: php
sudo: false

php:
  - 5.4

branches:
  except:
    - 7.x-1.x

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - UPGRADE=none
  - UPGRADE=7.x-2.26
  - UPGRADE=7.x-2.25
  - UPGRADE=7.x-2.24
  - UPGRADE=7.x-2.23
  - UPGRADE=7.x-2.22
  - UPGRADE=7.x-2.21
  - UPGRADE=7.x-2.20
  - UPGRADE=7.x-2.19
  - UPGRADE=7.x-2.18
  - UPGRADE=7.x-2.17
  - UPGRADE=7.x-2.16
  - UPGRADE=7.x-2.15
  - UPGRADE=7.x-2.14
  - UPGRADE=7.x-2.13
  - UPGRADE=7.x-2.12

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: UPGRADE=none
    - php: 5.5
      env: UPGRADE=7.x-2.23 TEST_FEATURES_OVERRIDES=1
    - php: 5.6
      env: UPGRADE=none

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Drupal.org verify tool
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # Build Behat dependencies
  - cd ./tests/behat
  - travis_retry composer install --prefer-dist --no-interaction
  - cd ../../../

  # Setting Behat environment
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - BEHAT_PARAMS='{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"BUILD_TOP/drupal"}}}}'
  - BEHAT_PARAMS=`echo $BEHAT_PARAMS | sed -e s#BUILD_TOP#$BUILD_TOP#`
  - export BEHAT_PARAMS

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv commerce_kickstart profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Build the current branch
  - cd drupal
  - drush make --yes profiles/commerce_kickstart/drupal-org-core.make --prepare-install
  - drush make --yes profiles/commerce_kickstart/drupal-org.make --no-core --contrib-destination=profiles/commerce_kickstart
  # Download Diff module for checking overridden features through Drush.
  - drush dl diff
  - cd ../

  # Verify that all the .make files will work on Drupal.org.
  - drush verify-makefile drupal/profiles/commerce_kickstart/drupal-org.make
  - find drupal/profiles/commerce_kickstart/modules -name \*.make -print0 | xargs -0 -n1 drush verify-makefile

  # Download an old version to test upgrading from.
  - if [[ "$UPGRADE" != none ]]; then drush dl commerce_kickstart-$UPGRADE; fi

  # Setup files
  - chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
  - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 5; done

   # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

  # Enable APC
  - |
    if [[ $TRAVIS_PHP_VERSION < "5.5" ]]; then
      echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo "apc.shm_size=256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

before_script:

  # Do the site install (either the current revision or old for the upgrade).
  - if [[ "$UPGRADE" == none ]]; then cd drupal; else cd commerce_kickstart-$UPGRADE; fi


  # Copy override module into sites/default/modules so it carries over when testing upgrades.
  - if [[ "$TEST_FEATURES_OVERRIDES" == 1 ]]; then mkdir sites/default/modules && cp -r ../drupal/profiles/commerce_kickstart/tests/commerce_kickstart_overrides_test sites/default/modules/commerce_kickstart_overrides_test; fi

  - drush si commerce_kickstart --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce Kickstart" --yes
  - drush pm-disable dblog --yes

  # If testing the override, enable it and revert feature it's overriding (because we didn't on the same install.)
  - if [[ "$TEST_FEATURES_OVERRIDES" == 1 ]]; then drush en -y commerce_kickstart_overrides_test && drush fr -y commerce_kickstart_blog; fi

  - cd ../drupal

  # If we're an upgrade test, run the upgrade process.
  - if [[ "$UPGRADE" != none ]]; then cp -a ../commerce_kickstart-$UPGRADE/sites/default/* sites/default/ && drush updb --yes; drush cc all;  fi

  # Start server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done
  - cd profiles/commerce_kickstart/tests/behat

script:

  # If this isn't an upgrade, we test if any features are overridden.
  - if [[ "$UPGRADE" == none ]]; then ../../scripts/check-overridden.sh; fi

  # Run Behat tests.
  - if [[ "$TEST_FEATURES_OVERRIDES" != 1 ]]; then ./bin/behat --config behat.travis.yml --tags ~@overrides; fi
  - if [[ "$TEST_FEATURES_OVERRIDES" == 1 ]]; then ./bin/behat --config behat.travis.yml --tags @overrides; fi

notifications:

  irc: "chat.freenode.net#drupal-commerce"
